### ISSUE TITLE
Initial DB

### ISSUE THREAD

**Issue by Chronyms** [ecamp/ecamp#20]
Please add an empty, initial Database.

**Comment by Chronyms** [comment]
Hab die Daten erhalten.
Somit geschlossen.

**Comment by carlobeltrame** [comment]
Die hätte ich aber auch gerne... ;) mache auch gerne einen PR mit einem SQL-Dump wenn ich die Schema habe.

**Comment by Chronyms** [comment]
Muss noch mein Git überarbeiten bis ich ein PR mache.
Kannst aber unter https://github.com/Chronyms/ecamp/tree/styling/backup/storage die DB herunterladen.
