### ISSUE TITLE
[BUG] Capcha wird nicht angezeigt - Registrierung nicht möglich

### ISSUE THREAD

**Issue by hannessolo** [ecamp/ecamp#53]
## Beschreibung

Auf der Produktiv-Seite können keine neuen Nutzer registreirt werden. Sobald "register" gedrückt wird, kommt die Meldung "Bitte Capcha richtig abschreiben".

Gestestet mit: Firefox 75, Chrome 80, Safari 12, Safari iOS 13

<img width="1336" alt="Screenshot 2020-04-24 at 17 41 18" src="https://user-images.githubusercontent.com/24207564/80230969-f5f2ed00-8652-11ea-8de1-b511d3af29a7.png">

Das reCaptcha wird auch nicht angezeigt:
<img width="458" alt="Screenshot 2020-04-24 at 18 02 23" src="https://user-images.githubusercontent.com/24207564/80232841-d7dabc00-8655-11ea-9be0-8b011b1ac962.png">

Die JavaScript Konsole hat folgendes zu Melden:
<img width="818" alt="Screenshot 2020-04-24 at 18 01 02" src="https://user-images.githubusercontent.com/24207564/80232853-dd380680-8655-11ea-8650-bc89fbb44c45.png">
<img width="896" alt="Screenshot 2020-04-24 at 18 01 27" src="https://user-images.githubusercontent.com/24207564/80232871-e3c67e00-8655-11ea-9d09-f902d2e7cb20.png">

**Comment by Vento-Nuenenen** [comment]
Merci für den Report.
Sollte mit #54 gelöst sein.

Anscheinend kollidiert seit kurzem die Mootools API mit recaptcha...

LG
Vento

**Comment by Vento-Nuenenen** [comment]
@hannessolo Sollte jetzt gelöst sein

**Comment by hannessolo** [comment]
Super, danke!
