### ISSUE TITLE
Lager / Update Koordinaten von Karte

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp#95]
- [x] Das Pop-Up Neue Koordinaten kommt, auch wenn man keine Rechte zum ändern hat --> Fehler
- [x] Bei Lagern wo ich das Recht zum ändern habe, muss ich zwei mal auf "Ja" clicken und dann noch die Seite neu laden

_Originally posted by @Vento-Nuenenen in https://github.com/ecamp/ecamp/pull/94#issuecomment-792290169_

**Comment by Vento-Nuenenen** [comment]
@pmattmann 
Könntest du schliessen.
